name: deploy_weasyprint

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
          python3-dev python3-pip rpm python3-rpm python3-venv

      - name: Prepare build environment
        run: |
          mkdir -p layer/out
          chmod +x ./build-layer.sh

      - name: Execute build script
        run: |
          ./build-layer.sh
        env:
          AWS_EXECUTION_ENV: "AWS_Lambda_python3.11"
          LAMBDA_RUNTIME_DIR: "/var/task"
