name: deploy_weasyprint

on:
  workflow_dispatch:

jobs:
  build-weasyprint-layer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build WeasyPrint Layer in Amazon Linux 2
        run: |
          docker pull amazonlinux:2 && docker run --rm -v "$(pwd):/workspace" -w /workspace amazonlinux:2 bash -c "
            set -e

            # Install required tools
            yum install -y yum-utils zip python3-pip rpmdevtools || { echo 'Failed to install tools'; exit 1; }

            # Create directories
            mkdir -p /workspace/tmp/layer/lib /workspace/tmp/layer/python

            # Download and extract required dependencies
            cd /workspace/tmp
            yumdownloader --resolve cairo gdk-pixbuf2 libffi pango expat libmount \
              libuuid libblkid glib2 libthai fribidi harfbuzz freetype graphite2 \
              libpng fontconfig shared-mime-info || { echo 'Failed to download dependencies'; exit 1; }

            mkdir -p /workspace/tmp/deps
            for rpm in *.rpm; do
              if rpm -qip "$rpm" >/dev/null 2>&1; then
                rpm2cpio "$rpm" | cpio -idm -D /workspace/tmp/deps || echo "Failed to extract: $rpm"
              else
                echo "Warning: Invalid RPM file: $rpm"
              fi
            done

            cp -r /workspace/tmp/deps/usr/lib64/* /workspace/tmp/layer/lib || echo "No libraries found to copy."

            # Standardize library symlinks
            find /workspace/tmp/layer/lib -type f -name 'lib*.so*' 2>/dev/null | while read -r f; do
              ln -sf $(basename "$f") /workspace/tmp/layer/lib/$(basename "$f" | sed 's/\.so\.\d*/.so/') || echo "Failed to create symlink for $f"
            done

            # Generate GDK Pixbuf loaders cache
            GDK_PIXBUF_MODULEDIR=$(find /workspace/tmp/layer/lib -name loaders 2>/dev/null | head -n 1)
            if [ -n "$GDK_PIXBUF_MODULEDIR" ]; then
              export GDK_PIXBUF_MODULEDIR
              GDK_PIXBUF_QUERY=$(find /workspace/tmp/deps/usr/bin -name gdk-pixbuf-query-loaders 2>/dev/null | head -n 1)
              if [ -n "$GDK_PIXBUF_QUERY" ]; then
                $GDK_PIXBUF_QUERY > /workspace/tmp/layer/lib/loaders.cache || echo "Failed to generate GDK Pixbuf loaders cache"
              else
                echo "Warning: gdk-pixbuf-query-loaders not found."
              fi
            else
              echo "Warning: GDK_PIXBUF_MODULEDIR not found."
            fi

            # Install WeasyPrint
            python3 -m pip install --no-cache-dir weasyprint -t /workspace/tmp/layer/python || { echo 'Failed to install WeasyPrint'; exit 1; }

            # Clean up unnecessary files
            find /workspace/tmp/layer/python -type d -name "tests" -exec rm -rf {} +
            find /workspace/tmp/layer/python -type d -name "*.dist-info" -exec rm -rf {} +

            # Package the layer
            cd /workspace/tmp/layer
            zip -r9 /workspace/tmp/weasyprint_layer.zip lib python || { echo 'Failed to create zip file'; exit 1; }
          "
