name: deploy_weasyprint

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          docker pull amazonlinux:2

      - name: Build Lambda Layer in Amazon Linux 2
        run: |
          docker run --rm -v "$(pwd)":/lambda-layer amazonlinux:2 /bin/bash -c "
          set -e
          yum update -y
          yum install -y rpmdevtools python3 python3-pip zip
          mkdir -p /lambda-layer/build
          cd /lambda-layer
          chmod +x ./build-layer.sh
          ./build-layer.sh
          "
        env:
          AWS_EXECUTION_ENV: "AWS_Lambda_python3.11"
          LAMBDA_RUNTIME_DIR: "/var/task"
